# Generated by Django 5.0.2 on 2024-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SETOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=4000)),
                ('unidade', models.CharField(max_length=10)),
                ('custo_unitario', models.FloatField()),
            ],
        ),
    ]
