# Generated by Django 5.0.2 on 2024-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=4000)),
                ('modalidade', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('comprador', models.CharField(max_length=255)),
                ('descrição', models.CharField(max_length=4000)),
                ('unidade', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
