# Generated by Django 5.0.2 on 2024-03-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setop',
            name='custo_unitario',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='setop',
            name='descricao',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='setop',
            name='unidade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
