# Generated by Django 5.0.2 on 2024-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principal', '0003_alter_setop_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setop',
            name='custo_unitario',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
